- name: Create a service account
  google.cloud.gcp_iam_service_account:
    name: "{{ service_account_name }}"
    display_name: "IAP Tunnel Service Account"
    project: "{{ project_id }}"
    state: present

- name: Assign IAP role to service account
  google.cloud.gcp_iam_policy:
    resource: "projects/{{ project_id }}"
    bindings:
      - role: "roles/iap.tunnelResourceAccessor"
        members:
          - "serviceAccount:{{ service_account_email }}"
      - role: "roles/compute.instanceAdmin.v1"
        members:
          - "serviceAccount:{{ service_account_email }}"